on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  release:
    name: release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install dependence
        run: |
          sudo apt-get update
          sudo apt-get -y install make git zlib1g-dev libssl-dev gperf cmake g++
      - name: build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --target install
          cd ..
          tar -czvf release.tar.gz /usr/local/bin/telegram-bot-api
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz"
          token: ${{ secrets.RELEASE_TOKEN }}